# bilibili-noads&beautify
# 开屏页广告,推荐页广告,动态(最常访问/推荐话题/列表广告),视频播放页面(up主推荐广告,相关推荐广告)
# 去除首页 tap 除推荐/热门/动画/影视以外的内容；去除首页 Bottom 的发布和会员购；右上角 top 只保留消息栏。
# Special thanks to app2smile, this version is base on app2smile's work - BiliBili去广告
hostname = app.bilibili.com, grpc.biliapi.net
^https:\/\/app\.bilibili\.com\/x\/(v2\/(splash\/(list|show)|feed\/index?)|resource\/(show\/tab\/v2|top\/activity)) url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/bilibili/bili-beautify.js
^https:\/\/app\.bilibili\.com\/x\/v2\/account\/(mine|mode\/status?) url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/bilibili/bili-beautify-account.js
^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/event\/list2? url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/bilibili/bili-beautify-splash.js
^https:\/\/app\.bilibili\.com\/bilibili\.app\.(view\.v1\.View\/View|dynamic\.v2\.Dynamic\/DynAll)$ url script-response-body https://raw.githubusercontent.com/app2smile/rules/master/js/bilibili-proto.js