# bilibili-beautify
# 去除首页 tap 除推荐/热门/动画/影视以外的内容；去除首页 Bottom 的发布和会员购；右上角 top 只保留消息栏。
# Special thanks to app2smile, this version is base on app2smile's BiliBili去广告
hostname = app.bilibili.com, grpc.biliapi.net
^https:\/\/app\.bilibili\.com\/x\/(v2\/(splash\/(list|show)|feed\/index\?)|resource\/show\/tab\/v2) url script-response-body https://raw.githubusercontent.com/gnl00/master/bilibili/bili-beautify.js