# 叮嗒出行 dingdatech-pure
hostname=game.dingdatech.com
^https:\/\/game\.dingdatech\.com\/page\/jc\/adConfig? url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/dingdatech/ddt-pure.js
^https:\/\/monitor\.ssp\.admobile\.top\/adReport? url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/dingdatech/ddt-splash-pure.js