# xhs-pure
# 1. remove save watermark [DONE]
# 2. remove home unused tabbar and categories [DONE]
# 3. remove ads [WORKING]
hostname=edith.xiaohongshu.com, xiaohongshu.com
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/(v1\/system_service\/config|v2\/(note\/feed?|system_service\/splash)|v6\/homefeed\/categories?) url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/xiaohongshu/xhs-pure.js