# 酷安 coolapk-pure
hostname=api.coolapk.com
^https:\/\/api\.coolapk\.com\/v6\/(main\/indexV8?|feed\/(detail|replyList)) url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/coolapk/coolapk-pure.js