# weibo-pure
# remove recommand video
hostname=api.weibo.cn
^https:\/\/api\.weibo\.cn\/2\/video\/tiny_stream_video_list?  url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/weibo/weibo-pure.js