# weibo-pure
# 微博国际版|极速版: 热搜过滤，移除综艺、电影、剧集内容；移除文娱榜
# remove recommand video [NOT WORK]
hostname=api.weibo.cn, weibointl.api.weibo.cn
^https:\/\/api\.weibo\.cn\/2\/(video\/tiny_stream_video_list?|!\/multimedia\/playback\/batch_get) url reject-dict
^https:\/\/api\.weibo\.cn\/2\/video\/tiny_stream_channel_list? url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/weibo/weibo-pure.js
^https:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=(search_topic|search_discover) url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/weibo/weibo-pure.js
^https:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?ct=feed&a=(search_topic|trends) url script-response-body https://raw.githubusercontent.com/gnl00/qtx/master/weibo/weibo-pure.js
